"""Pydantic schemas for 小信 API (contract v2.1)."""

from app.schemas.admin import AdminLoginReq, AdminLoginResp, ServiceConfig, ServiceConfigUpdate
from app.schemas.classroom import (
    ClassroomStatus,
    ControlReq,
)
from app.schemas.common import ErrorEnvelope, HealthCheck
from app.schemas.growth import (
    AcademicRecord,
    AcademicRecordInput,
    AcademicSummary,
    Commitment,
    EvidenceItem,
    GrowthView,
    ManualAcademicEntry,
    PetState,
    ScoreCard,
    SubjectScore,
)
from app.schemas.job import JobError, JobRef, JobStatus
from app.schemas.lesson import (
    LessonGenReq,
    LessonMaterial,
    LessonPlan,
    LessonSummary,
    TraceCreate,
)
from app.schemas.letter import Letter
from app.schemas.session import (
    ClassCreateReq,
    ClassCreateResp,
    ClassInfo,
    ClassPetView,
    EnterReq,
    EnterResp,
    StudentCreate,
    StudentProfile,
    TeacherClassesResp,
    TeacherClassView,
    TeacherEnterReq,
    TeacherEnterResp,
    TeacherProfile,
    TeacherSwitchReq,
)
from app.schemas.voice import (
    AudioChunkEvent,
    CommitTurnEvent,
    ImageEvent,
    SessionEndEvent,
    SessionStartedEvent,
    TranscriptEvent,
    TurnEndEvent,
    VADEndEvent,
    VADStartEvent,
    VoiceErrorEvent,
    VoiceMode,
    VoiceSessionReq,
)

__all__ = [
    "AcademicRecord",
    "AcademicRecordInput",
    "AcademicSummary",
    "AdminLoginReq",
    "AdminLoginResp",
    "ClassInfo",
    "ClassPetView",
    "ClassroomStatus",
    "Commitment",
    "ControlReq",
    "EnterReq",
    "EnterResp",
    "ErrorEnvelope",
    "EvidenceItem",
    "GrowthView",
    "HealthCheck",
    "JobError",
    "JobRef",
    "JobStatus",
    "LessonGenReq",
    "LessonMaterial",
    "LessonPlan",
    "LessonSummary",
    "Letter",
    "ManualAcademicEntry",
    "PetState",
    "ScoreCard",
    "ServiceConfig",
    "ServiceConfigUpdate",
    "StudentCreate",
    "StudentProfile",
    "SubjectScore",
    "TeacherEnterReq",
    "TeacherEnterResp",
    "TeacherProfile",
    "TraceCreate",
    "TeacherClassesResp",
    "TeacherClassView",
    "TeacherSwitchReq",
    "ClassCreateReq",
    "ClassCreateResp",
    "AudioChunkEvent",
    "CommitTurnEvent",
    "ImageEvent",
    "SessionEndEvent",
    "SessionStartedEvent",
    "TranscriptEvent",
    "TurnEndEvent",
    "VADEndEvent",
    "VADStartEvent",
    "VoiceErrorEvent",
    "VoiceMode",
    "VoiceSessionReq",
]
