"""Static/demo constants shared across the backend."""

REGION_NAMES: dict[str, str] = {
    "yunnan": "云南山区",
    "guizhou": "贵州梯田",
    "sichuan": "四川盆地",
    "gansu": "甘肃戈壁",
    "shaanxi": "陕西黄土",
    "guangxi": "广西丘陵",
    "qinghai": "青海高原",
    "ningxia": "宁夏平原",
    "xinjiang": "新疆绿洲",
    "xizang": "西藏雪域",
    "neimenggu": "内蒙古草原",
    "henan": "河南中原",
    "hunan": "湖南湘江",
    "hubei": "湖北荆楚",
    "jiangxi": "江西赣鄱",
    "anhui": "安徽江淮",
    "shanxi": "山西三晋",
    "shandong": "山东齐鲁",
    "hebei": "河北燕赵",
    "jiangsu": "江苏江南",
    "zhejiang": "浙江钱塘",
    "fujian": "福建闽越",
    "guangdong": "广东岭南",
    "hainan": "海南椰岛",
    "liaoning": "辽宁辽东",
    "jilin": "吉林长白",
    "heilongjiang": "黑龙江黑土",
    "beijing": "北京京华",
    "shanghai": "上海申城",
    "tianjin": "天津津门",
    "chongqing": "重庆山城",
}
